# -*- coding: utf-8 -*-
"""Titanic_Solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_WfJrUP8Ke32OJEkLDKXxj-ULFhBvY-
"""

# INSTITUTO FEDERAL DO AMAZONAS - CMZL
#   Professor: Carlos Mar
#       Curso: Introdução a Aprendizagem de Máquina
#       Aluna: Stefany Caroline Ferreira dos Santos

#   Atividade: Implementação de regressão logística para o disastre do Titanic
#   Descrição: Prediz quem sobreviverá ao desastre do Titanic utilizando regressão logística
# Última mod.: 01/12/2021

# Bibliotecas
import numpy as np
import pandas as pd
import math
from sklearn.linear_model import LogisticRegression

# Carrega as tabelas de dados de treino e de teste
treino_dados = pd.read_csv("https://raw.githubusercontent.com/santosscf/TitanicDisaster/main/Dataset/train.csv")
teste_dados = pd.read_csv("https://raw.githubusercontent.com/santosscf/TitanicDisaster/main/Dataset/test.csv")

# Modelagem: Regressão Logística
modelo = LogisticRegression(penalty='none', solver='newton-cg')

y = treino_dados["Survived"]

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
X = pd.get_dummies(treino_dados[features])
X_teste = pd.get_dummies(teste_dados[features])

# Tratando informações nulas do 'treino_dados'
    # Age - Substituição dos dados nulos pela média das idades
idadeMedia = math.floor(X['Age'].mean())
X.update(X['Age'].fillna(idadeMedia))

# Tratando informações nulas do 'teste_dados' 
    # Age - Substituição dos dados nulos pela média das idades
idadeMedia2 = math.floor(X_teste['Age'].mean())
X_teste.update(X_teste['Age'].fillna(idadeMedia2))

    # Fare - Substituição por média das taxas
taxaMedia = math.floor(X_teste['Fare'].mean())
X_teste.update(X_teste['Fare'].fillna(taxaMedia))

modelo.fit(X, y)

# Predizendo as probabilidades
teste_predictions = modelo.predict(X_teste)

output = pd.DataFrame({'PassengerId': teste_dados.PassengerId, 'Survived': teste_predictions})
output.to_csv('submission.csv', index=False)